import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { ensurePdfFont, getTableFont } from './fonts';

export interface DistributionPdfData {
  fromDate: string;
  toDate: string;
  totalProduction: number;
  farmProduction: number;
  collectionCenterProduction: number;
  storeDispatched: number;
  storeReceived: number;
  storeDiscrepancy: number;
  plantDispatched: number;
  plantRevenue: number;
  creamExtracted: number;
  ffmGenerated: number;
  cashSales: number;
  mixing: number;
  
  cowBreakdown: {
    farmEvening: number;
    farmMorning: number;
    ccEvening: number;
    ccMorning: number;
    storeTotal: number;
    creamTotal: number;
    ffmToCalves: number;
    ffmToPlant: number;
    ffmToDahi: number;
  };
  
  buffaloBreakdown: {
    ccEvening: number;
    ccMorning: number;
    storeTotal: number;
    plantTotal: number;
    plantRevenue: number;
  };
  
  images: {
    distributionPie: string;
    sourceComparison: string;
    monthlyTrends: string;
    speciesDonut: string;
  };
}

const inr = (num: number): string => {
  return `Rs.${Math.round(num).toLocaleString('en-IN')}`;
};

const fmtDate = (dateStr: string): string => {
  try {
    return format(new Date(dateStr), 'dd-MM-yyyy');
  } catch {
    return dateStr;
  }
};

function drawHeaderFooter(
  doc: jsPDF,
  meta: { range: string }
) {
  const totalPages = doc.internal.pages.length - 1;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Distribution Report', 18, 40);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(`Range: ${meta.range}`, pageWidth - 18, 42, { align: 'right' });

    doc.setFontSize(9);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Maharani Dairy', 18, pageHeight - 10);
    doc.text(`Page ${i} / ${totalPages}`, pageWidth - 18, pageHeight - 10, { align: 'right' });
    doc.setTextColor(0, 0, 0);
  }
}

export const generateDistributionReportPDF = (data: DistributionPdfData): jsPDF => {
  const doc = new jsPDF('p', 'pt', 'a4');
  ensurePdfFont(doc);
  
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  let yPos = 80;

  // PAGE 1: SUMMARY + DISTRIBUTION OVERVIEW
  const cardWidth = (pageWidth - 3 * margin) / 2;
  const cardHeight = 60;

  // KPI Cards (2x2 grid)
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.rect(margin, yPos, cardWidth, cardHeight);
  doc.rect(margin + cardWidth + margin / 2, yPos, cardWidth, cardHeight);

  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text('Total Production', margin + 8, yPos + 20);
  doc.text('Store Dispatch vs Receipt', margin + cardWidth + margin / 2 + 8, yPos + 20);

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(`${data.totalProduction.toFixed(1)} L`, margin + 8, yPos + 45);
  doc.text(`${data.storeDispatched.toFixed(1)} L → ${data.storeReceived.toFixed(1)} L`, margin + cardWidth + margin / 2 + 8, yPos + 45);

  yPos += cardHeight + 8;
  doc.setFont('helvetica', 'normal');
  doc.rect(margin, yPos, cardWidth, cardHeight);
  doc.rect(margin + cardWidth + margin / 2, yPos, cardWidth, cardHeight);

  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text('Plant Dispatch + Revenue', margin + 8, yPos + 20);
  doc.text('Cream + FFM', margin + cardWidth + margin / 2 + 8, yPos + 20);

  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text(`${data.plantDispatched.toFixed(1)} L`, margin + 8, yPos + 40);
  doc.setFontSize(11);
  doc.text(`Revenue: ${inr(data.plantRevenue)}`, margin + 8, yPos + 55);

  doc.setFontSize(16);
  doc.text(`${data.creamExtracted.toFixed(1)} L`, margin + cardWidth + margin / 2 + 8, yPos + 40);
  doc.setFontSize(11);
  doc.text(`FFM: ${data.ffmGenerated.toFixed(1)} L`, margin + cardWidth + margin / 2 + 8, yPos + 55);

  yPos += cardHeight + 25;

  // Distribution Overview Chart
  if (data.images.distributionPie) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Distribution Overview', margin, yPos);
    yPos += 10;
    
    const imgWidth = pageWidth - 2 * margin;
    const imgHeight = 280;
    doc.addImage(data.images.distributionPie, 'PNG', margin, yPos, imgWidth, imgHeight);
  }

  // PAGE 2: COW - SOURCE & SESSION BREAKDOWN
  doc.addPage();
  yPos = 70;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('COW - SOURCE & SESSION BREAKDOWN', margin, yPos);
  yPos += 5;
  
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(1);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 20;

  // Farm Production
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(41, 128, 185);
  doc.text(`Source: Farm (${data.cowBreakdown.farmEvening + data.cowBreakdown.farmMorning} L)`, margin, yPos);
  doc.setTextColor(0, 0, 0);
  yPos += 18;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`├─ Yesterday Evening (${data.cowBreakdown.farmEvening.toFixed(1)} L)`, margin + 5, yPos);
  yPos += 14;
  doc.text(`│  ├─ Store: ${data.cowBreakdown.storeTotal.toFixed(1)} L`, margin + 10, yPos);
  yPos += 14;
  doc.text(`│  └─ Other distributions`, margin + 10, yPos);
  yPos += 20;

  doc.text(`└─ Today Morning (${data.cowBreakdown.farmMorning.toFixed(1)} L)`, margin + 5, yPos);
  yPos += 14;
  doc.text(`   ├─ Cream Use: ${data.cowBreakdown.creamTotal.toFixed(1)} L`, margin + 10, yPos);
  yPos += 14;
  doc.text(`   │  ├─ FFM: ${data.ffmGenerated.toFixed(1)} L`, margin + 15, yPos);
  yPos += 14;
  doc.text(`   │  │  ├─ To Calves: ${data.cowBreakdown.ffmToCalves.toFixed(1)} L`, margin + 20, yPos);
  yPos += 14;
  doc.text(`   │  │  ├─ To Plant: ${data.cowBreakdown.ffmToPlant.toFixed(1)} L`, margin + 20, yPos);
  yPos += 14;
  doc.text(`   │  │  └─ To Dahi: ${data.cowBreakdown.ffmToDahi.toFixed(1)} L`, margin + 20, yPos);
  yPos += 20;

  // Collection Center
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(41, 128, 185);
  doc.text(`Source: Collection Center (${data.cowBreakdown.ccEvening + data.cowBreakdown.ccMorning} L)`, margin, yPos);
  doc.setTextColor(0, 0, 0);
  yPos += 25;

  // Summary box
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('SUMMARY', margin, yPos);
  yPos += 15;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`├─ Total Production: ${(data.cowBreakdown.farmEvening + data.cowBreakdown.farmMorning).toFixed(1)} L`, margin + 5, yPos);
  yPos += 14;
  doc.text(`├─ Store Dispatch: ${data.cowBreakdown.storeTotal.toFixed(1)} L`, margin + 5, yPos);
  yPos += 14;
  doc.text(`├─ Cream Use: ${data.cowBreakdown.creamTotal.toFixed(1)} L`, margin + 5, yPos);
  yPos += 14;
  
  const discrepancy = data.storeDiscrepancy;
  const discrepancyStatus = Math.abs(discrepancy) < 2 ? '✓ acceptable' : '⚠ review';
  doc.text(`└─ Discrepancy: ${discrepancy.toFixed(1)} L (${discrepancyStatus})`, margin + 5, yPos);

  // PAGE 3: BUFFALO - SOURCE & SESSION BREAKDOWN
  doc.addPage();
  yPos = 70;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('BUFFALO - SOURCE & SESSION BREAKDOWN', margin, yPos);
  yPos += 5;
  
  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(1);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 20;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('Source: Farm (0 L)', margin, yPos);
  yPos += 25;

  doc.setTextColor(41, 128, 185);
  doc.text(`Source: Collection Center (${data.buffaloBreakdown.ccEvening + data.buffaloBreakdown.ccMorning} L)`, margin, yPos);
  doc.setTextColor(0, 0, 0);
  yPos += 18;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`├─ Yesterday Evening (${data.buffaloBreakdown.ccEvening.toFixed(1)} L)`, margin + 5, yPos);
  yPos += 14;
  doc.text(`│  ├─ Store: ${(data.buffaloBreakdown.storeTotal * 0.4).toFixed(1)} L`, margin + 10, yPos);
  yPos += 14;
  doc.text(`│  ├─ Plant: ${(data.buffaloBreakdown.plantTotal * 0.5).toFixed(1)} L`, margin + 10, yPos);
  yPos += 14;
  doc.text(`│  ├─ Mixing: ${data.mixing.toFixed(1)} L`, margin + 10, yPos);
  yPos += 14;
  doc.text(`│  └─ Cash Sale: ${data.cashSales.toFixed(1)} L`, margin + 10, yPos);
  yPos += 20;

  doc.text(`└─ Today Morning (${data.buffaloBreakdown.ccMorning.toFixed(1)} L)`, margin + 5, yPos);
  yPos += 14;
  doc.text(`   ├─ Store: ${(data.buffaloBreakdown.storeTotal * 0.6).toFixed(1)} L`, margin + 10, yPos);
  yPos += 14;
  doc.text(`   └─ Plant: ${(data.buffaloBreakdown.plantTotal * 0.5).toFixed(1)} L`, margin + 10, yPos);
  yPos += 25;

  // Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.text('SUMMARY', margin, yPos);
  yPos += 15;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.text(`├─ Total Collection: ${(data.buffaloBreakdown.ccEvening + data.buffaloBreakdown.ccMorning).toFixed(1)} L`, margin + 5, yPos);
  yPos += 14;
  doc.text(`├─ Store Dispatch: ${data.buffaloBreakdown.storeTotal.toFixed(1)} L`, margin + 5, yPos);
  yPos += 14;
  doc.text(`├─ Plant Dispatch: ${data.buffaloBreakdown.plantTotal.toFixed(1)} L (${inr(data.buffaloBreakdown.plantRevenue)})`, margin + 5, yPos);
  yPos += 14;
  doc.text(`└─ Store Received: ${data.storeReceived.toFixed(1)} L`, margin + 5, yPos);

  // PAGE 4: CHARTS
  doc.addPage();
  yPos = 70;

  if (data.images.sourceComparison) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Source Comparison', margin, yPos);
    yPos += 10;

    const imgWidth = pageWidth - 2 * margin;
    const imgHeight = 200;
    doc.addImage(data.images.sourceComparison, 'PNG', margin, yPos, imgWidth, imgHeight);
    yPos += imgHeight + 25;
  }

  if (data.images.monthlyTrends && yPos + 220 < pageHeight - 50) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Monthly Trends', margin, yPos);
    yPos += 10;

    const imgWidth = pageWidth - 2 * margin;
    const imgHeight = 200;
    doc.addImage(data.images.monthlyTrends, 'PNG', margin, yPos, imgWidth, imgHeight);
  } else if (data.images.monthlyTrends) {
    doc.addPage();
    yPos = 70;
    
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('Monthly Trends', margin, yPos);
    yPos += 10;

    const imgWidth = pageWidth - 2 * margin;
    const imgHeight = 200;
    doc.addImage(data.images.monthlyTrends, 'PNG', margin, yPos, imgWidth, imgHeight);
  }

  const range = `${fmtDate(data.fromDate)} to ${fmtDate(data.toDate)}`;
  drawHeaderFooter(doc, { range });

  return doc;
};

export const generateDistributionWhatsAppMessage = (data: {
  fromDate: string;
  toDate: string;
  totalProduction: number;
  farmProduction: number;
  collectionCenterProduction: number;
  storeDispatched: number;
  storeReceived: number;
  plantDispatched: number;
  plantRevenue: number;
}): string => {
  let message = `*🥛 MILK DISTRIBUTION REPORT*\n`;
  message += `Date: ${fmtDate(data.fromDate)}${data.fromDate !== data.toDate ? ` to ${fmtDate(data.toDate)}` : ''}\n\n`;
  
  message += `*TOTAL PRODUCTION: ${data.totalProduction.toFixed(1)} L*\n`;
  message += `Farm: ${data.farmProduction.toFixed(1)} L | CC: ${data.collectionCenterProduction.toFixed(1)} L\n\n`;
  
  message += `*DISTRIBUTION*\n`;
  message += `Store: ${data.storeDispatched.toFixed(1)} L\n`;
  message += `Plant: ${data.plantDispatched.toFixed(1)} L (${inr(data.plantRevenue)})\n\n`;
  
  message += `*VERIFICATION*\n`;
  const discrepancy = data.storeDispatched - data.storeReceived;
  const status = Math.abs(discrepancy) < 2 ? '✓' : '⚠';
  message += `${status} Store: ${data.storeDispatched.toFixed(1)}L → ${data.storeReceived.toFixed(1)}L (${discrepancy >= 0 ? '+' : ''}${discrepancy.toFixed(1)}L)\n`;
  
  return message;
};
